# Generated by Django 4.0.5 on 2022-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank='True', max_length=30),
        ),
    ]
