<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-20 21:43
=======
# Generated by Django 4.0.5 on 2022-06-20 20:34
>>>>>>> 73717476984a8c4618b33161ccc775979912a41c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
